### ISSUE TITLE
Allow callers to specify a custom matrix for reusable workflows

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/.github#72]
In https://github.com/wp-cli/dist-archive-command/pull/78, I wanted to skip running the test workflow against PHP 5.6 and 7.0.

https://github.com/wp-cli/dist-archive-command/pull/78/commits/54027e64c6ece999bcac3a43f5058435deedd69b was my attempt, but it didn't work. It spawned jobs for every value in my matrix + every value in the reusable workflow matrix.

It would be helpful if a caller could specify a custom matrix. Alternatively, a caller could exclude specific values of the existing matrix.

**Comment by swissspidy** [comment]
I think this is completed now with #87
